# Generated by Django 5.2.6 on 2025-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_individuo', models.CharField(max_length=20)),
                ('nom_lab', models.CharField(max_length=100)),
                ('id_material', models.CharField(max_length=20)),
                ('volumen_actual', models.FloatField()),
                ('unidad_volumen', models.CharField(max_length=10)),
                ('concentracion_actual', models.FloatField()),
                ('unidad_concentracion', models.CharField(max_length=10)),
                ('masa_actual', models.FloatField()),
                ('unidad_masa', models.CharField(max_length=10)),
                ('fecha_extraccion', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_inicial', models.CharField(choices=[('CONG', 'Congelado'), ('REF', 'Refrigerado'), ('AMB', 'Ambiente')], max_length=50)),
                ('centro_procedencia', models.CharField(max_length=100)),
                ('lugar_procedencia', models.CharField(max_length=100)),
            ],
        ),
    ]
