# Generated by Django 5.2.6 on 2025-11-17 19:02

import django.db.models.deletion
import muestras.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_individuo', models.CharField(max_length=20)),
                ('nom_lab', models.CharField(max_length=100, unique=True)),
                ('id_material', models.CharField(blank=True, max_length=20, null=True)),
                ('volumen_actual', models.FloatField(blank=True, null=True)),
                ('unidad_volumen', models.CharField(blank=True, max_length=15, null=True)),
                ('concentracion_actual', models.FloatField(blank=True, null=True)),
                ('unidad_concentracion', models.CharField(blank=True, max_length=15, null=True)),
                ('masa_actual', models.FloatField(blank=True, null=True)),
                ('unidad_masa', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_extraccion', models.DateField(blank=True, null=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_inicial', models.CharField(blank=True, choices=[('CONG', 'Congelado'), ('REF', 'Refrigerado'), ('AMB', 'Ambiente')], max_length=50, null=True)),
                ('centro_procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_actual', models.CharField(blank=True, choices=[('DISP', 'Disponible'), ('ENV', 'Enviada'), ('ENVP', 'Parcialmente enviada'), ('DEST', 'Destruida')], default='Disponible', max_length=50, null=True)),
            ],
            options={
                'permissions': [('can_view_muestras_web', 'Puede ver muestras en la web'), ('can_add_muestras_web', 'Puede añadir muestras en la web'), ('can_change_muestras_web', 'Puede cambiar muestras en la web'), ('can_delete_muestras_web', 'Puede eliminar muestras en la web')],
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudio', models.CharField(max_length=20, unique=True)),
                ('referencia_estudio', models.CharField(max_length=100)),
                ('nombre_estudio', models.CharField(max_length=100)),
                ('descripcion_estudio', models.TextField(blank=True, null=True)),
                ('fecha_inicio_estudio', models.DateField()),
                ('fecha_fin_estudio', models.DateField(blank=True, null=True)),
                ('investigador_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudio', to='muestras.muestra', to_field='nom_lab')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=muestras.models.ruta_documentos)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateField(blank=True, null=True)),
                ('usuario_subida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudio', to='muestras.estudio', to_field='id_estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_enviado', models.FloatField()),
                ('unidad_volumen_enviado', models.CharField(max_length=15)),
                ('concentracion_enviada', models.FloatField()),
                ('unidad_concentracion_enviada', models.CharField(max_length=15)),
                ('centro_destino', models.CharField(max_length=100)),
                ('lugar_destino', models.CharField(max_length=100)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='muestras.muestra')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congelador', models.CharField(max_length=50)),
                ('estante', models.CharField(blank=True, max_length=50)),
                ('posicion_rack_estante', models.CharField(blank=True, max_length=50)),
                ('rack', models.CharField(blank=True, max_length=50)),
                ('posicion_caja_rack', models.CharField(blank=True, max_length=50)),
                ('caja', models.CharField(blank=True, max_length=50)),
                ('subposicion', models.IntegerField(blank=True)),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizacion', to='muestras.muestra', to_field='nom_lab')),
            ],
            options={
                'unique_together': {('muestra', 'congelador', 'estante', 'posicion_rack_estante', 'rack', 'posicion_caja_rack', 'caja', 'subposicion')},
            },
        ),
    ]
