# Generated by Django 5.2.6 on 2025-10-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_individuo', models.CharField(max_length=20, unique=True)),
                ('nom_lab', models.CharField(max_length=100, unique=True)),
                ('id_material', models.CharField(max_length=20)),
                ('volumen_actual', models.FloatField()),
                ('unidad_volumen', models.CharField(max_length=15)),
                ('concentracion_actual', models.FloatField()),
                ('unidad_concentracion', models.CharField(max_length=15)),
                ('masa_actual', models.FloatField()),
                ('unidad_masa', models.CharField(max_length=15)),
                ('fecha_extraccion', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_inicial', models.CharField(choices=[('CONG', 'Congelado'), ('REF', 'Refrigerado'), ('AMB', 'Ambiente')], max_length=50)),
                ('centro_procedencia', models.CharField(max_length=100)),
                ('lugar_procedencia', models.CharField(max_length=100)),
                ('estado_actual', models.CharField(choices=[('DISP', 'Disponible'), ('ENV', 'Enviada'), ('ENVP', 'Parcialmente enviada'), ('DEST', 'Destruida')], default='Disponible', max_length=50)),
            ],
            options={
                'permissions': [('can_view_muestras_web', 'Puede ver muestras en la web'), ('can_add_muestras_web', 'Puede añadir muestras en la web'), ('can_change_muestras_web', 'Puede cambiar muestras en la web'), ('can_delete_muestras_web', 'Puede eliminar muestras en la web')],
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congelador', models.CharField(max_length=50)),
                ('estante', models.CharField(max_length=50)),
                ('posicion_rack_estante', models.CharField(max_length=50)),
                ('rack', models.CharField(max_length=50)),
                ('posicion_caja_rack', models.CharField(max_length=50)),
                ('caja', models.CharField(max_length=50)),
                ('subposicion', models.CharField(max_length=50)),
                ('id_individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizaciones_individuo', to='muestras.muestra', to_field='id_individuo')),
                ('nom_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizaciones_nom_lab', to='muestras.muestra', to_field='nom_lab')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudio', models.CharField(max_length=20)),
                ('referencia_estudio', models.CharField(max_length=100)),
                ('nombre_estudio', models.CharField(max_length=100)),
                ('descripcion_estudio', models.TextField(blank=True, null=True)),
                ('fecha_inicio_estudio', models.DateField()),
                ('fecha_fin_estudio', models.DateField(blank=True, null=True)),
                ('investigador_principal', models.CharField(max_length=100)),
                ('id_individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudio_individuo', to='muestras.muestra', to_field='id_individuo')),
                ('nom_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudio_nom_lab', to='muestras.muestra', to_field='nom_lab')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_enviado', models.FloatField()),
                ('unidad_volumen_enviado', models.CharField(max_length=15)),
                ('concentracion_enviada', models.FloatField()),
                ('unidad_concentracion_enviada', models.CharField(max_length=15)),
                ('centro_destino', models.CharField(max_length=100)),
                ('lugar_destino', models.CharField(max_length=100)),
                ('id_individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_individuo', to='muestras.muestra', to_field='id_individuo')),
                ('nom_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_nom_lab', to='muestras.muestra', to_field='nom_lab')),
            ],
        ),
    ]
