# Generated by Django 5.2.6 on 2025-10-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muestra',
            options={'permissions': [('can_view_muestras', 'Can view muestras'), ('can_add_muestras', 'Can add muestras'), ('can_change_muestras', 'Can change muestras'), ('can_delete_muestras', 'Can delete muestras')]},
        ),
    ]
