# Generated by Django 5.2.6 on 2025-10-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0002_alter_muestra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muestra',
            options={'permissions': [('can_view_muestras_web', 'Can view muestras'), ('can_add_muestras_web', 'Can add muestras'), ('can_change_muestras_web', 'Can change muestras'), ('can_delete_muestras_web', 'Can delete muestras')]},
        ),
    ]
