# Generated by Django 5.2.6 on 2025-11-18 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0003_alter_documento_usuario_subida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='fecha_inicio_estudio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='investigador_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='referencia_estudio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
