# Generated by Django 5.2.6 on 2025-10-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0003_alter_localizacion_muestra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localizacion',
            unique_together={('congelador', 'estante', 'posicion_rack_estante', 'rack', 'posicion_caja_rack', 'caja', 'subposicion')},
        ),
    ]
