# Generated by Django 5.2.6 on 2025-10-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0003_alter_muestra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muestra',
            options={},
        ),
    ]
