# Generated by Django 5.2.6 on 2025-11-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0004_alter_estudio_fecha_inicio_estudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudio', to='muestras.estudio'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='id_estudio',
            field=models.CharField(max_length=20),
        ),
    ]
