# Generated by Django 5.2.6 on 2025-10-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0004_alter_muestra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muestra',
            options={'permissions': [('can_view_muestras_web', 'Puede ver muestras en la web'), ('can_add_muestras_web', 'Puede añadir muestras en la web'), ('can_change_muestras_web', 'Puede cambiar muestras en la web'), ('can_delete_muestras_web', 'Puede eliminar muestras en la web')]},
        ),
    ]
