# Generated by Django 5.2.6 on 2025-10-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0004_alter_localizacion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizacion', to='muestras.muestra', to_field='nom_lab', unique=True),
        ),
    ]
