# Generated by Django 5.2.6 on 2025-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0005_alter_documento_estudio_alter_estudio_id_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='muestra',
        ),
        migrations.AddField(
            model_name='estudio',
            name='muestra',
            field=models.ManyToManyField(blank=True, null=True, related_name='estudio', to='muestras.muestra'),
        ),
    ]
