# Generated by Django 5.2.6 on 2025-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0006_alter_localizacion_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='caja',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='estante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='posicion_caja_rack',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='posicion_rack_estante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='rack',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='subposicion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
