# Generated by Django 5.2.6 on 2025-11-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0006_remove_estudio_muestra_estudio_muestra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='muestra',
        ),
        migrations.AddField(
            model_name='muestra',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestras.estudio'),
        ),
    ]
