# Generated by Django 5.2.6 on 2025-11-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0007_remove_estudio_muestra_muestra_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='estudio',
        ),
        migrations.AddField(
            model_name='muestra',
            name='estudio',
            field=models.ManyToManyField(blank=True, to='muestras.estudio'),
        ),
    ]
