# Generated by Django 5.2.6 on 2025-11-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0007_alter_localizacion_caja_alter_localizacion_estante_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localizacion',
            unique_together={('muestra', 'congelador', 'estante', 'posicion_rack_estante', 'rack', 'posicion_caja_rack', 'caja', 'subposicion')},
        ),
    ]
