# Generated by Django 5.2.6 on 2025-11-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0008_remove_muestra_estudio_muestra_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='id_estudio',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='nombre_estudio',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
