# Generated by Django 5.2.6 on 2025-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0008_alter_localizacion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='subposicion',
            field=models.IntegerField(blank=True),
        ),
    ]
