# Generated by Django 5.2.6 on 2025-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0009_alter_localizacion_subposicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='centro_procedencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='concentracion_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='estado_actual',
            field=models.CharField(blank=True, choices=[('DISP', 'Disponible'), ('ENV', 'Enviada'), ('ENVP', 'Parcialmente enviada'), ('DEST', 'Destruida')], default='Disponible', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='estado_inicial',
            field=models.CharField(blank=True, choices=[('CONG', 'Congelado'), ('REF', 'Refrigerado'), ('AMB', 'Ambiente')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='fecha_extraccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='id_material',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='lugar_procedencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='masa_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='unidad_concentracion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='unidad_masa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='unidad_volumen',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='volumen_actual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
