# Generated by Django 5.2.6 on 2025-11-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0009_alter_estudio_id_estudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='estudio',
            field=models.ManyToManyField(blank=True, null=True, to='muestras.estudio'),
        ),
    ]
