# Generated by Django 5.2.6 on 2025-11-23 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0010_alter_muestra_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='estudio',
        ),
        migrations.AddField(
            model_name='muestra',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestras.estudio', to_field='nombre_estudio'),
        ),
    ]
