# Generated by Django 5.2.6 on 2025-11-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0010_alter_muestra_centro_procedencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='concentracion_actual',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='fecha_extraccion',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='fecha_llegada',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='id_material',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='masa_actual',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='unidad_concentracion',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='unidad_masa',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='unidad_volumen',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='volumen_actual',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
