# Generated by Django 5.2.6 on 2025-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0011_remove_muestra_estudio_muestra_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='subposicion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
