# Generated by Django 5.2.6 on 2025-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0012_alter_localizacion_subposicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='congelador',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
