# Generated by Django 5.2.6 on 2025-11-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0012_alter_muestra_concentracion_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudio', to='muestras.muestra', to_field='nom_lab'),
        ),
    ]
