# Generated by Django 5.2.6 on 2025-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0013_alter_localizacion_congelador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='caja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='congelador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='estante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='posicion_caja_rack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='posicion_rack_estante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='rack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
