# Generated by Django 5.2.6 on 2025-11-23 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0014_alter_localizacion_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_envio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
