# Generated by Django 5.2.6 on 2025-11-25 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0016_envio_usuario_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estudios', to='muestras.estudio')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estudios', to='muestras.muestra')),
            ],
        ),
        migrations.CreateModel(
            name='historial_localizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_localizaciones', to='muestras.localizacion')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_localizaciones', to='muestras.muestra')),
            ],
        ),
    ]
