# Generated by Django 5.2.6 on 2025-11-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0018_historial_estudios_usuario_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_localizaciones',
            name='localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historial_localizaciones', to='muestras.localizacion'),
        ),
    ]
