# Generated by Django 5.2.6 on 2025-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0019_alter_historial_localizaciones_localizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=200, unique=True)),
                ('direccion', models.TextField()),
                ('persona_contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_contacto', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
