# Generated by Django 5.2.6 on 2025-11-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0020_agenda_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda_envio',
            name='centro',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='agenda_envio',
            name='lugar',
            field=models.CharField(max_length=200),
        ),
    ]
