# Generated by Django 5.2.6 on 2025-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0022_registro_destruido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congelador', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_minima', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_maxima', models.CharField(blank=True, max_length=50, null=True)),
                ('localizacion_edificio', models.CharField(blank=True, max_length=50, null=True)),
                ('fotografia', models.ImageField(upload_to='')),
            ],
        ),
    ]
