# Generated by Django 5.2.6 on 2025-12-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0023_congelador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congelador',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='congeladores/'),
        ),
    ]
