# Generated by Django 5.2.6 on 2025-12-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0024_alter_congelador_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_localizaciones',
            name='localizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_localizaciones', to='muestras.localizacion'),
        ),
    ]
