# Generated by Django 5.2.6 on 2025-12-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0025_alter_historial_localizaciones_localizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudio',
            options={'permissions': [('can_view_estudios_web', 'Puede ver estudios en la web'), ('can_add_estudios_web', 'Puede añadir estudios en la web'), ('can_change_estudios_web', 'Puede cambiar estudios en la web'), ('can_delete_estudios_web', 'Puede eliminar estudios en la web')]},
        ),
        migrations.AlterModelOptions(
            name='localizacion',
            options={'permissions': [('can_view_localizaciones_web', 'Puede ver localizaciones en la web'), ('can_add_localizaciones_web', 'Puede añadir localizaciones en la web'), ('can_change_localizaciones_web', 'Puede cambiar localizaciones en la web'), ('can_delete_localizaciones_web', 'Puede eliminar localizaciones en la web')]},
        ),
    ]
