# Generated by Django 5.2.6 on 2025-12-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0026_alter_estudio_options_alter_localizacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_estudios',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_estudios', to='muestras.estudio'),
        ),
    ]
