# Generated by Django 5.2.6 on 2025-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0027_alter_historial_estudios_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='estado_inicial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
