# Generated by Django 5.2.6 on 2025-12-18 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0028_alter_muestra_estado_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='investigadores_asociados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Investigadores'}, related_name='estudios_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='investigador_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
