# Generated by Django 5.2.6 on 2025-12-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0029_estudio_investigadores_asociados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='id_estudio',
        ),
    ]
